### ISSUE TITLE
Real-time Monitoring of Collect

### ISSUE THREAD

**Issue by KateBrodie** [FRF-Remote-Sensing/DuneLidar#12]
We need to implement something that monitors the collect computer to make sure it's doing what it's supposed ot be doing and if it doesn't, then it should alert us (e.g. email or text a group of us). 

I talked briefly with Kent about what he does, and he had some recommendations. Tristan, please talk with Kent about what we need to setup--sounds like GAIA will be involved since it has a portal between ISO and RDE (Kahuna does too, but it's too dumb to do anything). 

-Kate

**Comment by atdyer** [comment]
@KateBrodie will do. Sounds like something that'll be easier for me to set up while I'm there so this is high on my to-do list for next week when I'm back for FRF day.

**Comment by atdyer** [comment]
@KateBrodie 
Collect script now includes code that will tell GAIA to send an email to all of us if the collect goes down unexpectedly, and the email will contain info about what's wrong with the collect (e.g. can't connect to scanner, scanner is hung up, RAIDs are down, etc.). It's not up and running yet because Kent is updating his scripts next week, but all of the work on our end is done so I'm going to close this.
