### ISSUE TITLE
Label Usage and Milestones

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#28]
@atdyer @KateBrodie @njspore 

So I found out how to add new custom labels to this repository.  I wanted to be able to label some things as "low" priority and "high" priority.  I found a [link](http://programmers.stackexchange.com/questions/129714/how-to-manage-github-issues-for-priority-etc) where someone used: 
- prio:low
- prio:normal
- prio:high

I also found this:
- pri0-blocker
- pri1-critical
- pri2-high
- pri3-normal
- pri4-low

I also added a "Fall experiment" Milestone, so we can sort by issues that are milestone.

Thoughts? ideas? Maybe look around at other repos for ideas?

**Comment by atdyer** [comment]
@hokiespurs @KateBrodie @njspore 

I like the priority idea, but I'm not a huge fan of the way that guy does it. Why use something odd and abbreviated like 'prio:low' when you can just use 'low priority'?

Also, couldn't 'normal priority' things just be issues without a priority tag? Things that are clearly low priority and can wait indefinitely could be tagged 'low priority' and things that absolutely need to be finished immediately could be tagged 'high priority', while everything else could just be priority tag-less. I'm just trying to avoid a ton of tags that eventually become meaningless because everything has got them.

**Comment by hokiespurs** [comment]
Ok so lets start with these labels:

### Priority
- Priority: Low
- Priority: High
- Priority: CRITICAL ( FIRE ALARM! NEEDS TO BE DONE NOW NOW NOW)

### Type
- Type: Help Wanted (i dont know how to do something)
- Type: Bug (code is broken)
- Type: Discussion (these are general ideas, and could lead into an enhancement)
- Type: Enhancement
