### ISSUE TITLE
Line Range Filter Not Working

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/DuneLidar#6]
I can't make the Line Range Filter work.  

@atdyer , can you take a look at it?  It's in the latest push.  

The Rmat vector is decreasing, rather than increasing as your code expected, so i added a check in there but it didn't seem to fix it.

**Comment by atdyer** [comment]
Since Rmat is decreasing, you need to change line 59 to be <= instead of >= and line 96 to be >= instead of <=

**Comment by atdyer** [comment]
Also, #4 screws things up in the range filter, those points behind the scanner need a negative range so that they are ordered correctly

**Comment by hokiespurs** [comment]
Made a commit with a "testRangeFilter" script

Can you see what I'm doing wrong?  Below is the link to the commit on the line branch.

12f994db8dc4859d93588b82d21f29aa0638c1fe

**Comment by atdyer** [comment]
Okay I've figured out why things weren't working and the range filter is now fixed in the master branch. The problem was that the range filter, which expects a low-to-high scan, also expects the the first ```stencilSize``` points are good ground points. The test dataset we've been using has a bunch of NaNs at the beginning of each linescan, so a comparison with all NaNs resulted in the filter never passing. I've changed the filter to now initially fill the stencil with the first ```stencilSize``` non-NaN values before starting to filter. Here's a sample from the fixed version:

![filtered](https://cloud.githubusercontent.com/assets/4733059/9446200/4bf9086e-4a5e-11e5-94c4-f8375f0af3d0.png)

Two things about the current filter:
  - It still expects low-to-high scans, so flip your matrices before sending them to the filter. I've started on a new filter that will do a more robust check and filter things in the correct order.
  - Our test dataset still has that non-negative range thingy going on at the start of each line, so the filter will filter out a lot of those values. Passing in data that has negative values for distance from scanner will fix this.

**Comment by hokiespurs** [comment]
Nice!!

Here was my attempt at the low-high or high-low input option ec0aa8b22196f9a92d26c11c251ead449071f063

I've fixed the negative range and will pull request in the next few days.

**Comment by atdyer** [comment]
@hokiespurs 

Yup, I'm going to use that same test, but instead of flipping the matrices I'm going to reverse the order of the filter to avoid unnecessary data copies :metal:

**Comment by hokiespurs** [comment]
:+1:
good call!

**Comment by hokiespurs** [comment]
@atdyer Works well for me!

But, We might have to get creative with the fact that we see the back of the dune.  So the Z isnt always increasing as Range is decreasing.

![rangefilter](https://cloud.githubusercontent.com/assets/7690281/9457741/8f6d417c-4ab4-11e5-921a-95fcf7aca889.jpg)
